server:
  port: 5003
spring:
  application:
    name: email-service
  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
  config:
    import: configserver:http://lsa-config-service:9999/
